# Generated by Django 4.2.7 on 2024-04-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ManyToManyField(to='doctor.specialization'),
        ),
    ]
